# Generated by Django 3.2.12 on 2022-03-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=4096)),
                ('release_date', models.DateField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('rated_by', models.IntegerField()),
                ('movieID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.movies')),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='rating',
            field=models.ForeignKey(default='0', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.ratings'),
        ),
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=200, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movies')),
            ],
        ),
    ]
