# Generated by Django 3.2.12 on 2022-03-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_movies_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='rating',
            field=models.ForeignKey(default='0', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.ratings'),
        ),
    ]
