# Generated by Django 3.2.12 on 2022-03-22 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220321_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.ForeignKey(default='NA', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.ratings'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='movieID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.movies'),
        ),
    ]
