# Generated by Django 3.2.12 on 2022-03-21 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateField()),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movies')),
            ],
        ),
    ]
