# Generated by Django 3.2.12 on 2022-03-21 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ordered_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
