# Generated by Django 3.2.12 on 2022-03-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movieplay'),
        ('userAccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='item',
        ),
        migrations.AddField(
            model_name='orders',
            name='item',
            field=models.ManyToManyField(to='core.MoviePlay'),
        ),
    ]
