# Generated by Django 3.2.12 on 2022-03-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movieplay'),
        ('userAccount', '0002_auto_20220325_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='item',
        ),
        migrations.AddField(
            model_name='orders',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.movieplay'),
            preserve_default=False,
        ),
    ]
