# Generated by Django 3.2.12 on 2022-03-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0003_rename_itemid_orders_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
